production sync
clearpathrobotics/cpr-documentation pull request #271
Opened 2024-09-19 14:32 UTC by tonybaltovski

2024-09-19 15:23 UTC, jhiggins-cpr commented on docs_versioned_docs/version-ros2humble/robots/accessories/manipulators/kinova_gen3_lite.mdx
> -### Launching the ROS Driver {#kinova_gen3_lite_launch}
There is a reference to #kinova_gen3_lite_launch that now no longer resolves correctly. The reference should be fixed or removed.

2024-09-19 15:32 UTC, jhiggins-cpr commented on docs_versioned_docs/version-ros2humble/ros/ros.mdx
> + - [Kinova Gen3 Lite, 6Dof, and 7Dof Arms](./config/yaml/manipulators.mdx#kinova-arms)
The #kinova-arms anchor doesn't exist yet and should be added in manipulators.mdx.

2024-09-19 15:32 UTC, jhiggins-cpr commented on docs_versioned_docs/version-ros2humble/ros/ros.mdx
> + - [Robotiq 2F 85 and 140 Grippers](./config/yaml/manipulators.mdx#robotiq-grippers)
The #robotiq-grippers anchor doesn't exist yet and should be added in manipulators.mdx.

2024-09-19 15:33 UTC, jhiggins-cpr requested changes
There are a few broken anchors that would be good to fix before merging.

2024-09-23 22:55 UTC, tonybaltovski commented
Updated with fixed anchors.

2024-09-24 19:19 UTC, jhiggins-cpr approved these changes

2024-09-24 20:49 UTC, merged