Onav 1016
clearpathrobotics/cpr-documentation pull request #93
Opened 2023-03-27 13:51 UTC by dobrienCP

Contains the changes to the documentation reflecting the new Mission Manager UI updates.

2023-03-27 16:55 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/faq.mdx
> +6.  **The navigation gets stuck on the ""Compute Path"" feedback.
Can we change from "" to "?

2023-03-27 16:57 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +    Waypoint appears inbetween two other waypoints when in edit mode. The user can
"inbetween" -> "between"

2023-03-27 16:57 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +    drag and drop this ghost waypoint to add a new waypoint to the mission in between
"in between" -> "between"

2023-03-27 16:58 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +To create a new Mission to run on the UGV first ensure that the UI is in "Edit Mode" (
"To create a new Mission to run on the UGV" -> "To create a new Mission"

2023-03-27 16:58 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +which you can then add Waypoints to.
"to which you can then add Waypoints."

2023-03-27 17:25 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +As waypoints are placed, a "ghost waypoint" will appear between each real
"each real waypoints" -> "each pair of real Waypoints"

2023-03-27 17:26 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +waypoint and can be dragged to a new spot to insert a real Waypoint in
"in between" -> "between"

2023-03-27 17:28 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +2.  Click the name of the Waypoint which the user wants to rename.
We flip between the second person singlular ("you") and third person singular ("the user"). We should choose one or the other and be consistent throughout. Applies to other locations in this file as well.

2023-03-27 17:30 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +        often recommended to place the undock task first in the list of Waypoints;
"Task"

2023-03-27 17:30 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +        waypoint once undocked. See Section
"Waypoint"

2023-03-27 17:30 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +for the Waypoint. For example, when creating a mission to an inspection point,
"mission" -> "Waypoint"

2023-03-27 17:32 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +(ie. the robot will only align itself with the correct heading at The
"The waypoint" -> "the Waypoint"

2023-03-27 17:32 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +waypoint). If you need the robot to be at specific headings at
"Waypoint"

2023-03-27 17:32 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +other waypoints you'll need to enter these in for each specific Waypoint.
"Waypoints"

2023-03-27 17:33 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +mission has been started this button will turn green.
"Mission"

2023-03-27 17:33 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_overview.mdx
> +    indicators represent SBAS and SPP accuraciy respectively and noticeable
"accuracy"

2023-03-27 17:34 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_overview.mdx
> +    drag and drop waypoints in this mode. Once this button is enabled,
"Waypoints"

2023-03-27 17:34 UTC, jhiggins-cpr commented on docs_outdoornav_user_manual/web_user_interface/ui_overview.mdx
> +16. **Pause Button:** Pause the current mission. Pressing the start button
"Mission"

2023-03-27 17:37 UTC, jhiggins-cpr requested changes
Overall, looks ok to me, once we complete the minor changes noted throughout.

2023-03-28 00:06 UTC, dobrienCP commented on docs_outdoornav_user_manual/web_user_interface/ui_autonomous_mode.mdx
> +2.  Click the name of the Waypoint which the user wants to rename.
I'll try and keep it in 3rd person for now.

2023-03-28 11:45 UTC, jhiggins-cpr approved these changes

2023-03-28 13:06 UTC, merged